### PR TITLE
Update dependencies against vulnerabilities

### PR DESCRIPTION
**Pull request by jbcden**
Addresses [these](https://gemnasium.com/mobiledefense/google_safe_browsing/alerts) from gemnasium.

### CODE REVIEW

**Comment by bsiegel** [comment]
We should probably not pin the gem versions here at all, see:
http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

**Comment by bsiegel** [comment]
I've opened #23 which I think is the correct way to deal with these outdated dependencies. @chrismar035 any opinions?

**Comment by jbcden** [comment]
@chrismar035 @bsiegel Was this ready to be merged or waiting for more comments?

**Comment by chrismar035** [comment]
I'm good with this. Seems Travis is too now. Any other objections?

**Comment by jbcden** [comment]
This looks good to me. I might submit one more commit to update the patch number in the version

**Comment by chrismar035** [comment]
@jbcden I'll update the version right before pushing to rubygems. We don't need to do it in a specific PR.

**Comment by jbcden** [comment]
sounds good

**Pull request merged**
